### ISSUE TITLE
writing issues to SD

### ISSUE THREAD

**Issue by mega-stoffel** [Friends-of-OpenBikeSensor/OpenBikeSensorFirmware#1]
to avoid writing issues to the SD card, it might be good to wait until the bike (including the device) is not moving.
Without the shocks from the potentially rough roads, it might be more secure to execute write access to the SD card.

**Comment by tobst** [comment]
I was assuming that power off while writing could be a problem. A quick fix is to reduce the the number of write accesses and ask the user to push the button while powering off. But looking into th effects of rough roads is agood idea. The code does not handle failed writing attempts at all so far.

**Comment by 4n08o** [comment]
This would need an accel sensor first. -> HW change.
Improving the HW by PCB (removing all the hand wired cables) should improve the behaviour already.
