### ISSUE TITLE
Feedback during Update

### ISSUE THREAD

**Issue by mega-stoffel** [Friends-of-OpenBikeSensor/OpenBikeSensorFirmware#10]
when you're updating the Firmware via the WLAN-connection, please give some feedback, if the "update-button" is already working. Some progress bar or changing the color/pattern of the "update" button would help.

**Comment by mega-stoffel** [comment]
just realized, that there is some feedback. Using an iPhone, you get a progress bar.
This does not appear on my windows laptop or on my android phone.

**Comment by boldt** [comment]
Which browsers (versions) exaclty?

I tested it with:

* Firefox 76.0.1 (Desktop / Ubuntu 18.04)
* Chrome 80.0 (Desktop / Ubuntu 18.04)
* Opera 68.0 (Desktop / Ubuntu 18.04)

**Comment by boldt** [comment]
Fixed with a506f47b905dadfb6207d1bed1a26de57339d43f
