### ISSUE TITLE
Anzeigen, ob WLAN-Passwort hinterlegt wurde.

### ISSUE THREAD

**Issue by Natenom** [Friends-of-OpenBikeSensor/OpenBikeSensorFirmware#100]
Aktuell ist im WLAN Untermenü nur die eingegebene SSID zu sehen, aber nicht, ob man ein Passwort bereits angegeben hat.

**Comment by boldt** [comment]
Ich zeige nun wenn ein Passwort hinterlegt ist ****** an.
