### ISSUE TITLE
Konfiguration herunterladen/hochladen

### ISSUE THREAD

**Issue by Natenom** [Friends-of-OpenBikeSensor/OpenBikeSensorFirmware#101]
Es wäre schön, wenn man die aktuelle Konfiguration herunterladen/hochladen könnte. Gerade die Einrichtung der PrivacyZones ist sehr umständlich,wenn die Konfiguration mal wieder verloren geht. Das passiert bei mir immer wieder, wenn der Akku leer ist, ich das nicht weiß und das Gerät trotzdem wieder einschalte.

**Comment by boldt** [comment]
Gute Idee!

**Comment by Natenom** [comment]
Vielleicht auch die Konfiguration in eine Datei auf der SD-Karte auslagern/einlesen?

**Comment by boldt** [comment]
Schaue ich mir beides näher an.

**Comment by boldt** [comment]
@Natenom Fertig implementiert. Bitte einmal testen.
