### ISSUE TITLE
"Back to Main Menu"

### ISSUE THREAD

**Issue by Natenom** [Friends-of-OpenBikeSensor/OpenBikeSensorFirmware#112]
Aktuell kann man oben über das verlinkte "OpenBikeSensor" zum Hauptmenü zurück.

Es wäre besser, wenn es unten auch einen Button dafür geben würde.

**Comment by boldt** [comment]
Warum?

**Comment by Natenom** [comment]
Weil das nicht für jeden direkt ersichtlich ist. War es anfangs für mich auch nicht, habe dann immer die URL in der Adressleiste bearbeitet.
