### ISSUE TITLE
Display Misbehavior in Simple Mode

### ISSUE THREAD

**Issue by mega-stoffel** [Friends-of-OpenBikeSensor/OpenBikeSensorFirmware#128]
in the Simple Display Mode (only the passing distance shown, nothing else), there's a small misbehavior. Sometimes it shows "---" when there's no car passing, sometimes it shows "--- cm".
Probably not serious, but maybe worth to fix, anyways.

**Comment by amandel** [comment]
See also #58

**Comment by amandel** [comment]
Fixed with above commit

**Comment by boldt** [comment]
Thanks :)
