### ISSUE TITLE
Remove binaries from the repo

### ISSUE THREAD

**Issue by boldt** [Friends-of-OpenBikeSensor/OpenBikeSensorFirmware#13]
A repo should only contain the code, not the final binary. 

* Use the "Releases" provided by Github:
    * https://help.github.com/en/enterprise/2.13/user/articles/creating-releases

**Comment by mega-stoffel** [comment]
here's the latest documentation, even though it's probably identical:
--> https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository

**Comment by tobst** [comment]
Solved with commit 69d9d8a6f0b52dc935e2ce06fbc42b8b943b40f6 and release of v0.1.0
