### ISSUE TITLE
Check and enhance display during measurement

### ISSUE THREAD

**Issue by tobst** [Friends-of-OpenBikeSensor/OpenBikeSensorFirmware#20]
The font size selected seemed to be the biggest fitting on the screen. In order to add status information like number of satellites etc. position and size should be adapted and a suitable font size for the status line as well as display class member functions for displaying should be added.

**Comment by uwewoessner** [comment]
I had to use a smaller font anyway because the generated font header was broken.
We probably could use a larger font again if we limit it to numbers only.
The font is still too large to display both distances

**Comment by boldt** [comment]
Fixed with b0aea8212ec62cbddccc23d6cc5f9305b586fba9

![IMG_20200522_151036](https://user-images.githubusercontent.com/750793/82671865-d3e38f00-9c3f-11ea-8844-4e2540d08bc2.jpg)
