### ISSUE TITLE
Fix webserver

### ISSUE THREAD

**Issue by tobst** [Friends-of-OpenBikeSensor/OpenBikeSensorFirmware#22]
Uploading a binary through the sensor webserver has worked on IPhone and Firefox on a MacBook Pro. Adroid or Windows crashed while Uploading with "File not found"

**Comment by boldt** [comment]
Which browsers (version)?

**Comment by boldt** [comment]
Should be fixed with 7a45d788ee4dc593aef3427ca108abeb47198e65
