### ISSUE TITLE
Line endings

### ISSUE THREAD

**Issue by boldt** [Friends-of-OpenBikeSensor/OpenBikeSensorFirmware#25]
We should define which line ending we want to use in the whole project, since WIndows, Linux and MAC use different ones.

@uwewoessner - see this commits:

* https://github.com/Friends-of-OpenBikeSensor/OpenBikeSensorFirmware/commit/171118b1d367f5b85606b750ca895f658b5206d7
* https://github.com/Friends-of-OpenBikeSensor/OpenBikeSensorFirmware/commit/3df08362d4ce3f814df06cb28d454acdd680a1bd
* https://github.com/Friends-of-OpenBikeSensor/OpenBikeSensorFirmware/commit/9aac760345f06fd178e304f0d5a83a4b8b2451b2

Unfortunately, the whole files changed. I guess you just changed some lines.

I made some changes, which I didnt commit yet. They are not mergable.

See here:

* https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings

**Comment by boldt** [comment]
If I change one line, I have the same issue now:

![Bildschirmfoto von 2020-05-18 19-46-35](https://user-images.githubusercontent.com/750793/82243749-66ceb180-9940-11ea-9865-8147da4ff4b3.png)

**Comment by boldt** [comment]
@uwewoessner - you changed the files to Windows file endings. 

TODO:

* [ ] Convert all file to the same file ending
* [ ] Add a `.gitattribues`, which handles the line endings for all users

**Comment by boldt** [comment]
Could be fixed with #24

**Comment by boldt** [comment]
# Analysis

## Windows Endings (CRLF) 

```bash
dennis@denpc:~/git/OpenBikeSensorFirmware$ file *.h *.ino | grep CRLF
config.h:                   C source, ASCII text, with CRLF line terminators
configServer.h:             C source, ASCII text, with CRLF line terminators
displays.h:                 C++ source, ASCII text, with CRLF line terminators
sensor.h:                   C++ source, ASCII text, with CRLF line terminators
config.ino:                 ASCII text, with CRLF line terminators
configServer.ino:           HTML document, UTF-8 Unicode text, with CRLF line terminators
OpenBikeSensorFirmware.ino: C source, ASCII text, with CRLF line terminators
sensor.ino:                 ASCII text, with CRLF line terminators
```

## Linux Endings

```bash
dennis@denpc:~/git/OpenBikeSensorFirmware$ file *.h *.ino | grep -v CRLF
font.h:                     ASCII text, with very long lines
gps.h:                      C source, ASCII text
logo.h:                     ASCII text
vector.h:                   C++ source, ASCII text
writer.h:                   C++ source, ASCII text
gps.ino:                    ASCII text
ota.ino:                    ASCII text
writer.ino:                 ASCII text
```

See: https://stackoverflow.com/a/3570574/605890

**Comment by uwewoessner** [comment]
added  .gitattributes, should be fixed now
