### ISSUE TITLE
Display gets crazy sometimes

### ISSUE THREAD

**Issue by Natenom** [Friends-of-OpenBikeSensor/OpenBikeSensorFirmware#27]
Sometimes the bottom part of the measured value is on top of the screen and the top part is on the bottom. Must turn off/on to fix that.

**Comment by boldt** [comment]
I did plenty of improvements on the display (no new release yet). 
Can you show me a picture of this issue to understand it fully? Thx.

**Comment by Natenom** [comment]
https://files.natenom.com/s/1719d.jpg

**Comment by boldt** [comment]
Ich glaube das tritt auf, wenn die Batterie sich dem Ende neigt. Dann ist das Display unterversorgt und  "buggt" - zumindest scheint das bei dem OBS von @mega-stoffel der Fall zu sein. Ich beobachte weiter

**Comment by boldt** [comment]
![image_from_ios](https://user-images.githubusercontent.com/750793/82709581-3315c380-9c81-11ea-81d3-3db0e9902e92.jpg)
![image_from_ios2](https://user-images.githubusercontent.com/750793/82709582-33ae5a00-9c81-11ea-87cd-8acbef6d828b.jpg)
![IMG_20200522_123426](https://user-images.githubusercontent.com/750793/82709584-3446f080-9c81-11ea-9dca-8cccc0d8ca72.jpg)
![IMG_20200522_123827](https://user-images.githubusercontent.com/750793/82709586-3446f080-9c81-11ea-8de3-84a71af8b23c.jpg)
![IMG_20200522_123831](https://user-images.githubusercontent.com/750793/82709588-34df8700-9c81-11ea-86ec-003f846f5b5a.jpg)
![IMG_20200522_124053](https://user-images.githubusercontent.com/750793/82709590-34df8700-9c81-11ea-9b7f-19dddcbabf11.jpg)
![IMG_20200522_142820](https://user-images.githubusercontent.com/750793/82709591-35781d80-9c81-11ea-8181-34a5d5c70dc6.jpg)
![IMG_20200522_154822](https://user-images.githubusercontent.com/750793/82709593-35781d80-9c81-11ea-87b8-68672d153e50.jpg)

**Comment by boldt** [comment]
Hardware issue, which is fixed with a pull-up resistor on the board
