### ISSUE TITLE
Show device information while starting up

### ISSUE THREAD

**Issue by tobst** [Friends-of-OpenBikeSensor/OpenBikeSensorFirmware#3]
Show the version number, number of gps satellites, success of sd card mount while starting up, and display information on connecting when in config mode

**Comment by boldt** [comment]
Fixed with: 

* 9a1d5b63eb54640d3e0a5b9ed1d6840e9adc97bc
* e3cd6b27e081e1c918e24d80b55e3041ad1fbc95
* fd1f9645467e2786679b6a49f86bb424db5809a5
* add3c17b5f7a5ac8de2b39b17c04b4cd46844880

See: https://photos.app.goo.gl/cG9FLQ8Hyz2o7yyXA
