### ISSUE TITLE
WLAN-Modus aktivieren, wenn kein Display angeschlossen ist

### ISSUE THREAD

**Issue by Natenom** [Friends-of-OpenBikeSensor/OpenBikeSensorFirmware#37]
Das Display mit dem Knopf ist normalerweise am Fahrrad montiert. Das Gerät nimmt man zum Laden etc mit. Wenn man aber ein Update machen möchte, dann muss man entweder mit Laptop zum Fahrrad gehen oder das display abmontieren.

Deshalb sollte der WLAN-Modus automatisch starten, wenn man das Gerät aktiviert und kein Display angeschlossen ist.

**Comment by tobst** [comment]
Sollte mit v0.1.8 und fc8751ecd210628a905289200238c7e746618f2d funktionieren.
