### ISSUE TITLE
provide option for "easy display"

### ISSUE THREAD

**Issue by mega-stoffel** [Friends-of-OpenBikeSensor/OpenBikeSensorFirmware#50]
it would be good, to have a very easy understandable display. It should show only the passing distance, maybe including "cm". This might be helpful for upcoming "marketing" activities. A single value on the display, which everyone can understand without further explanation would be a good thing.

**Comment by boldt** [comment]
# Config

![Bildschirmfoto von 2020-05-24 16-38-25](https://user-images.githubusercontent.com/750793/82756911-53f32b80-9ddd-11ea-910b-2f4d55115f59.png)

# Display

![IMG_20200524_163657 (1)](https://user-images.githubusercontent.com/750793/82756915-581f4900-9ddd-11ea-88c6-b6324986358a.jpg)
