### ISSUE TITLE
Handle maximum program size

### ISSUE THREAD

**Issue by boldt** [Friends-of-OpenBikeSensor/OpenBikeSensorFirmware#51]
> Sketch uses 912706 bytes (69%) of program storage space. Maximum is 1310720 bytes.

* 1310720 / 1024 = 1280 kByte = 1,25 MB

Why only 1,2 MB? We use the partition scheme `Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS)` in the Arduino IDE.

What causes memory:

* OTA
* The SPIFFS partition

Conclusions:
* The ESP32 has 4MB flash memory.
* OTA needs memory to "store" the new binary.
* We do not need the 1.5MB SPIFFS
* In Arduino IDE, we can use the partition scheme `1.9MB APP with OTA/190KB SPIFFS`

> Sketch uses 912706 bytes (46%) of program storage space. Maximum is 1966080 bytes.

TODO: 
* [ ] Flash existing OBSs with new partition scheme

Resources: 
* https://esp32.com/viewtopic.php?f=19&t=14420
* https://forum.arduino.cc/index.php?topic=578847.0
* https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/ota.html
* https://github.com/espressif/arduino-esp32/issues/2802

**Comment by boldt** [comment]
https://sparks.gogo.co.nz/avr-ram-use.html

**Comment by 4n08o** [comment]
I presume, that our binary gets bigger and bigger.  We have huge memory on the SD Card.  Just for the update, is it feasible to temporarily store the OTA binary there and update from there?

**Comment by amandel** [comment]
With v0.3. - merging the bluetooth branch the new partition schema was rolled out to the master.
