### ISSUE TITLE
HC-SR04 with interrupts instead of pulseIn()

### ISSUE THREAD

**Issue by boldt** [Friends-of-OpenBikeSensor/OpenBikeSensorFirmware#73]
* http://kunoichi.be/projects/arduino-and-detecting-objects-with-multiple-hc-sr04-sensor/
* http://kunoichi.be/projects/multiple-hc-sr04-with-arduino-using-only-1-interrupt-pin/
* https://homediyelectronics.com/projects/arduino/arduinoprogramminghcsr04withinterrupts/?p=4

**Comment by boldt** [comment]
* http://www.nerdkits.com/forum/thread/2216/
* http://www.nerdkits.com/forum/thread/2183/

**Comment by amandel** [comment]
Implemented with #124 (I did not realize the reference before)
