### ISSUE TITLE
Test high quality sd-cards

### ISSUE THREAD

**Issue by tobst** [Friends-of-OpenBikeSensor/OpenBikeSensorFirmware#85]
Also consider sd-card errors could be due to low quality sd-cards. If all software solutions fail, look into different manufactures/qulaities of sd-cards.

**Comment by Natenom** [comment]
Genau das mache ich aktuell :)

Bisher beim ersten Auslesen nach zwei Tagen keine Probleme.

* 28180 Datensätze (entspricht ca. 7,8 Stunden)
* 258 bestätige Datensätze (Knopf gedrückt)

**Comment by Natenom** [comment]
Seit ich eine gute SD-Karte verwende, gab es kein einziges Mal defekte Daten. Ich mache deshalb hier mal zu.
