### ISSUE TITLE
Rename folder `OpenBikeSensorFirmware` to `src`

### ISSUE THREAD

**Issue by boldt** [Friends-of-OpenBikeSensor/OpenBikeSensorFirmware#88]
Wha do you think @tharkay @DanielHabenicht 

(**Hint**: Use `git mv`)

**Comment by tharkay** [comment]
The Arduino IDE needs the folder name and the .ino file name to match (for whatever reason). I totally agree, that a `src` directory would look much better! After changing the folder name, I get this error:  ![error](https://user-images.githubusercontent.com/6745803/86977205-6acac300-c17c-11ea-9f5b-2b203e51e0a5.png)

Changing this folder would make the project incompatible with the Arduino IDE. Although the question remains if we still want to support that IDE ...

**Comment by amandel** [comment]
Any objections against renaming? Is someone still using Arduino IDE for OBS development - please shout ;)
