### ISSUE TITLE
Version-Number on Start Page

### ISSUE THREAD

**Issue by mega-stoffel** [Friends-of-OpenBikeSensor/OpenBikeSensorFirmware#9]
put the version number on the start page, when you're connecting to the sensor via WLAN.
Then you immediately know, which version you're running. This might help for future debugging issues.

**Comment by boldt** [comment]
![Screenshot_20200519-154949](https://user-images.githubusercontent.com/750793/82335181-4444a300-99e9-11ea-8fe8-898947dbfe06.png)
